[general]
working_directory = "None"
live_config_reload = true

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 100, lines = 30 }
dynamic_padding = true
decorations = "Full"
opacity = 0.8
title = "Alacritty@CachyOS"
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }
italic = { family = "monospace", style = "Italic" }
bold_italic = { family = "monospace", style = "Bold Italic" }
size = 12.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x0D0D0D"
foreground = "0xE5E5E5"

[colors.normal]
black   = "0x090909"
red     = "0xE53935"
green   = "0x8A8A8A"
yellow  = "0xFF8C00"
blue    = "0x5A5A5A"
magenta = "0x8F1D1A"
cyan    = "0xB85C00"
white   = "0xC7C7C7"

[colors.bright]
black   = "0x2A2A2A"
red     = "0xFF3B30"
green   = "0xC7C7C7"
yellow  = "0xFF8C00"
blue    = "0x8A8A8A"
magenta = "0xE53935"
cyan    = "0xD96F00"
white   = "0xE5E5E5"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

bindings = [
    { mouse = "Middle", mods = "None", action = "PasteSelection" },
]

[keyboard]
bindings = [
    { key = "Paste", mods = "None", action = "Paste" },
    { key = "Copy", mods = "None", action = "Copy" },
    { key = "L", mods = "Control", action = "ClearLogNotice" },
    { key = "L", mods = "Control", mode = "~Vi", chars = "\f" },
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ScrollPageDown" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ScrollToTop" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ScrollToBottom" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "F", mods = "Control|Shift", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward" },
    { key = "C", mods = "Control|Shift", mode = "Vi", action = "ClearSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
]
